modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="spoiledeggs"
version="${file.jarVersion}"
displayName="Spoiled Eggs"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-curse-update-checker.herokuapp.com/523343"
logoFile="icon.png"
authors="Grend"
description="Adds spoiled eggs and zombie chickens!"

[[dependencies.spoiledeggs]]
	modId="forge"
	mandatory=true
	versionRange="[36,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.spoiledeggs]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.16.5]"
	ordering="NONE"
	side="BOTH"

[[dependencies.spoiledeggs]]
	modId="iceberg"
	mandatory=true
	versionRange="[1.0.8,)"
	ordering="NONE"
	side="BOTH"
